load("//third_party/cpplint:cpplint.bzl", "cpplint")

cc_binary(
    name = "move_constructor_and_assignment",
    srcs = ["move_constructor_and_assignment.cc"],
    deps = ["@gperftools//:tcmalloc_and_profiler"],
)

cpplint()
