#!/bin/bash
#------- qsub option -----------
#PBS -q SQUID-H
#PBS --group=jh220009
#PBS -N sam
#PBS -j o
#PBS -b 1
#PBS -l gpunum_job=1
#PBS -l elapstim_req=100:00:00

module load BaseGPU/2021
source /sqfs/home/z6b038/vir/py3/bin/activate

export PYTHONPATH=$PYTHONPATH:/sqfs/home/z6b038/.local/lib/python3.8/site-packages
export PYTHONPATH=$PYTHONPATH:/sqfs/home/z6b038/common

export http_proxy="http://ibgw1f-ib0:3128"
export https_proxy="https://ibgw1f-ib0:3128"

cd $PBS_O_WORKDIR

wandb agent --count 8 2nd-order-opt-survey/pai/tnxk27vt
