#!/bin/bash

#SBATCH -J ivon
#YBATCH -r any_1
#SBATCH -N 1
#$ -l h_rt=72:00:00

source /etc/profile.d/modules.sh
module load cuda/11.4
module load cudnn/cuda-11.4

source $HOME/vir/py3/bin/activate
export PYTHONPATH=$PYTHONPATH:$HOME/asdfghjkl:$PYTHONPATH:$HOME/common:$HOME/sam:$HOME/vit-pytorch


#wandb agent --count 5 2nd-order-opt-survey/ivon/9pf6stu4 # lr
wandb agent --count 5 2nd-order-opt-survey/ivon/fex3bvvu # dp
