#!/bin/bash

#SBATCH -J PaI
#YBATCH -r any_1
#SBATCH -N 1
#$ -l h_rt=72:00:00

source /etc/profile.d/modules.sh
module load cuda/11.4
module load cudnn/cuda-11.4

source $HOME/vir/py3/bin/activate
export PYTHONPATH=$PYTHONPATH:$HOME/asdfghjkl:$PYTHONPATH:$HOME/common:$HOME/sam:$HOME/vit-pytorch

python 13_pai.py \
  --device=cuda \
  --dataset=CIFAR10 \
  --model=cifar_resnet_20 \
  --lr=0.03 \
  --batch-size=128 \
  magnitude
  #obs
