#!/bin/bash

#SBATCH -J prunning
#YBATCH -r any_1
#SBATCH -N 1
#$ -l h_rt=72:00:00

source /etc/profile.d/modules.sh
module load cuda/11.4
module load cudnn/cuda-11.4

source $HOME/vir/py3/bin/activate
export PYTHONPATH=$PYTHONPATH:$HOME/asdfghjkl:$PYTHONPATH:$HOME/common

python 11_cifar10.py \
  --model resnet18 \
  --dataset CIFAR10 \
  --label-smoothing 0 \
  --opt kfac \
  --batch-size 512 \
  --lr 0.4 \
  --epochs 90 \
  --warmup-epochs 0 \
  --lr-decay-epoch 30 50 70 \
  --lr-decay-rate 0.1
