name: CI

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    - name: Build
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" build -- //... -//titech/...

    - name: Test
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test --config=disable_heap_check -- //... -//titech/...

    - name: Coverage
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" coverage -- //... -//titech/...

    - name: Cpplint
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test --config=cpplint -- //... -//titech/...

    - name: GenPages
      run: |
        third_party/genhtml/genhtml bazel-out/_coverage/_coverage_report.dat -o /tmp/coverage

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: /tmp/coverage
